// Regenerate options modal — toggles for happy/sad/AI scenario generation.
// Replaces the old separate AI checkbox in the plan header + generic confirm.

import { h } from "../dom";
import { openModal } from "../modal";

export interface RegenerateChoice {
  include_happy: boolean;
  include_sad: boolean;
  include_ai: boolean;
}

interface Opts {
  defaults?: Partial<RegenerateChoice>;
}

export function openRegenerateOptions(opts: Opts = {}): Promise<RegenerateChoice | null> {
  return new Promise((resolve) => {
    const choice: RegenerateChoice = {
      include_happy: opts.defaults?.include_happy ?? true,
      include_sad: opts.defaults?.include_sad ?? true,
      include_ai: opts.defaults?.include_ai ?? false,
    };

    const toggle = (
      label: string,
      description: string,
      key: keyof RegenerateChoice,
    ): HTMLElement => {
      const btn = h("button.toggle", {
        "data-on": choice[key] ? "true" : "false",
        onclick: () => {
          choice[key] = !choice[key];
          btn.setAttribute("data-on", choice[key] ? "true" : "false");
          btn.textContent = choice[key] ? "ON" : "OFF";
        },
      }, choice[key] ? "ON" : "OFF");

      return h(".toggle-row",
        h(".toggle-meta",
          h(".toggle-label", label),
          h(".toggle-desc.muted.mono", { style: { fontSize: "11px" } }, description),
        ),
        btn,
      );
    };

    const body = h("div",
      h(".muted", { style: { marginBottom: "var(--s-4)" } },
        "Pick which kinds of test cases to produce. Existing cases are replaced."),
      toggle("Happy Path", "2xx success cases from each endpoint's documented responses.", "include_happy"),
      toggle("Sad Path", "Negative scenarios: bad IDs, missing required fields, unauthorized, etc.", "include_sad"),
      toggle("AI scenarios", "Domain-specific edge cases generated by the configured AI model.", "include_ai"),
    );

    let resolved = false;
    const finish = (result: RegenerateChoice | null) => {
      if (resolved) return;
      resolved = true;
      close();
      resolve(result);
    };

    const cancelBtn = h("button.btn.ghost", { onclick: () => finish(null) }, "Cancel");
    const goBtn = h("button.btn.primary", {
      onclick: () => {
        if (!choice.include_happy && !choice.include_sad && !choice.include_ai) {
          // Nothing selected — treat as cancel instead of producing an empty plan.
          finish(null);
          return;
        }
        finish(choice);
      },
    }, "Regenerate →");

    const close = openModal({
      title: "Regenerate Plan",
      body,
      actions: [cancelBtn, goBtn],
      dismissOnBackdrop: false,
      onClose: () => finish(null),
    });
  });
}
