// Regenerate options modal — toggles for happy/sad/AI scenario generation.
// Replaces the old separate AI checkbox in the plan header + generic confirm.

import { getAIStatus, getConfig } from "../api";
import { h } from "../dom";
import { openModal } from "../modal";

export interface RegenerateChoice {
  include_happy: boolean;
  include_sad: boolean;
  include_ai: boolean;
}

interface Opts {
  defaults?: Partial<RegenerateChoice>;
}

export function openRegenerateOptions(opts: Opts = {}): Promise<RegenerateChoice | null> {
  return new Promise((resolve) => {
    const choice: RegenerateChoice = {
      include_happy: opts.defaults?.include_happy ?? true,
      include_sad: opts.defaults?.include_sad ?? true,
      include_ai: opts.defaults?.include_ai ?? false,
    };

    let aiAvailable = true;
    let aiBtn: HTMLButtonElement | null = null;
    let aiDescEl: HTMLElement | null = null;

    const toggle = (
      label: string,
      description: string,
      key: keyof RegenerateChoice,
    ): { row: HTMLElement; btn: HTMLButtonElement; descEl: HTMLElement } => {
      const btn = h("button.toggle", {
        "data-on": choice[key] ? "true" : "false",
        onclick: () => {
          if (key === "include_ai" && !aiAvailable) return;
          choice[key] = !choice[key];
          btn.setAttribute("data-on", choice[key] ? "true" : "false");
          btn.textContent = choice[key] ? "ON" : "OFF";
        },
      }, choice[key] ? "ON" : "OFF") as HTMLButtonElement;

      const descEl = h(".toggle-desc.muted.mono", { style: { fontSize: "11px" } }, description);
      const row = h(".toggle-row",
        h(".toggle-meta",
          h(".toggle-label", label),
          descEl,
        ),
        btn,
      );
      return { row, btn, descEl };
    };

    const happy = toggle("Happy Path", "2xx success cases from each endpoint's documented responses.", "include_happy");
    const sad = toggle("Sad Path", "Negative scenarios: bad IDs, missing required fields, unauthorized, etc.", "include_sad");
    const ai = toggle("AI scenarios", "Domain-specific edge cases generated by the configured AI model.", "include_ai");
    aiBtn = ai.btn;
    aiDescEl = ai.descEl;

    const body = h("div",
      h(".muted", { style: { marginBottom: "var(--s-4)" } },
        "Pick which kinds of test cases to produce. Existing cases are replaced."),
      happy.row,
      sad.row,
      ai.row,
    );

    // Probe AI availability — if the server has no model configured, disable the
    // toggle and explain why instead of letting the user enable a no-op.
    Promise.all([getAIStatus(), getConfig().catch(() => null)])
      .then(([status, config]) => {
        const enabled = !!status.enabled;
        const available = !!status.available;
        aiAvailable = enabled && available;
        if (!aiAvailable && aiBtn && aiDescEl) {
          choice.include_ai = false;
          aiBtn.setAttribute("data-on", "false");
          aiBtn.textContent = "OFF";
          aiBtn.disabled = true;
          aiBtn.style.opacity = "0.5";
          aiBtn.style.cursor = "not-allowed";
          const provider = (status.provider as string | undefined)
            || (config?.ai_provider as string | undefined)
            || (config?.ai_backend as string | undefined)
            || "local_gguf";
          aiDescEl.textContent = enabled
            ? `AI provider "${provider}" not reachable — check Settings → AI.`
            : `AI is disabled (provider: ${provider}) — enable it in Settings → AI to use scenarios.`;
          aiDescEl.style.color = "var(--warning, #f59e0b)";
        }
      })
      .catch(() => {
        aiAvailable = false;
        if (aiBtn && aiDescEl) {
          aiBtn.disabled = true;
          aiBtn.style.opacity = "0.5";
          aiBtn.style.cursor = "not-allowed";
          aiDescEl.textContent = "Could not reach AI status endpoint.";
        }
      });

    let resolved = false;
    const finish = (result: RegenerateChoice | null) => {
      if (resolved) return;
      resolved = true;
      close();
      resolve(result);
    };

    const cancelBtn = h("button.btn.ghost", { onclick: () => finish(null) }, "Cancel");
    const goBtn = h("button.btn.primary", {
      onclick: () => {
        if (!choice.include_happy && !choice.include_sad && !choice.include_ai) {
          // Nothing selected — treat as cancel instead of producing an empty plan.
          finish(null);
          return;
        }
        finish(choice);
      },
    }, "Regenerate →");

    const close = openModal({
      title: "Regenerate Plan",
      body,
      actions: [cancelBtn, goBtn],
      dismissOnBackdrop: false,
      onClose: () => finish(null),
    });
  });
}
