"""Engine facade — the single entry point for all business logic.

The `Engine` class wraps parsing, plan generation, merge logic, persistence,
and history. TUI and Web UI call into this facade; they do not touch parsing,
execution, or storage modules directly.

Design rules:
- The engine is stateless w.r.t. UI. It does not hold "current spec" or
  "current plan" — callers pass those in and receive results back.
- All storage goes through the injected `Storage` implementation.
- No UI imports, no Textual, no FastAPI. Pure Python.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from specs_agent.config import AppConfig, add_recent_spec
from specs_agent.models.plan import TestCase, TestPlan
from specs_agent.models.results import Report
from specs_agent.models.spec import ParsedSpec
from specs_agent.parsing.extractor import extract_spec
from specs_agent.parsing.loader import SpecLoadError, last_warnings, load_spec
from specs_agent.parsing.plan_generator import generate_plan

from specs_agent.engine.storage import FileStorage, Storage


@dataclass
class SpecLoadResult:
    """Return value for `Engine.load_spec_from_source`."""
    spec: ParsedSpec
    source: str
    source_type: str  # "url" | "file" | "clipboard"
    warnings: list[str]


@dataclass
class MergeResult:
    """Return value for `Engine.merge_plans`."""
    plan: TestPlan
    kept: int
    new: int
    removed: int


class Engine:
    """Facade over parsing, plan gen, persistence, and execution."""

    def __init__(self, storage: Storage | None = None) -> None:
        self.storage: Storage = storage or FileStorage()

    # ------------------------------------------------------------------
    # Config
    # ------------------------------------------------------------------

    def load_config(self) -> AppConfig:
        return self.storage.load_config()

    def save_config(self, config: AppConfig) -> None:
        self.storage.save_config(config)

    def record_recent_spec(self, config: AppConfig, source: str, title: str) -> None:
        """Update config's recent-specs list and persist."""
        add_recent_spec(config, source, title)
        self.save_config(config)

    # ------------------------------------------------------------------
    # Spec loading
    # ------------------------------------------------------------------

    @staticmethod
    def classify_source(source: str) -> str:
        if source.startswith(("http://", "https://")):
            return "url"
        if "/.specs-agent/pasted/" in source:
            return "clipboard"
        return "file"

    def load_spec_from_source(self, source: str) -> SpecLoadResult:
        """Load and parse a spec from a URL or file path.

        Raises `SpecLoadError` on failure. Callers are expected to handle
        it and surface the error to the user.
        """
        raw = load_spec(source)
        spec = extract_spec(raw, source_url=source)
        warnings = list(last_warnings.warnings)
        return SpecLoadResult(
            spec=spec,
            source=source,
            source_type=self.classify_source(source),
            warnings=warnings,
        )

    @staticmethod
    def specs_differ(old: ParsedSpec | None, new: ParsedSpec) -> bool:
        """Return True if the raw spec JSON differs between old and new."""
        if old is None:
            return True
        try:
            old_json = json.dumps(old.raw_spec, sort_keys=True)
            new_json = json.dumps(new.raw_spec, sort_keys=True)
            return old_json != new_json
        except Exception:
            return True

    # ------------------------------------------------------------------
    # Specs persistence
    # ------------------------------------------------------------------

    def save_spec(self, title: str, source: str, source_type: str, raw_spec: dict) -> str:
        return self.storage.save_spec(title, source, source_type, raw_spec)

    def list_saved_specs(self, limit: int = 20) -> list[dict]:
        return self.storage.list_specs(limit)

    def load_saved_spec(self, spec_id: str) -> dict | None:
        return self.storage.load_spec(spec_id)

    def delete_saved_spec(self, spec_id: str) -> bool:
        return self.storage.delete_spec(spec_id)

    # ------------------------------------------------------------------
    # Plan generation & merging
    # ------------------------------------------------------------------

    def generate_plan(self, spec: ParsedSpec) -> TestPlan:
        """Generate a fresh plan from a parsed spec.

        If AI is enabled in config and a model is available, complex fields
        are generated by the LLM instead of Faker templates.
        """
        config = self.storage.load_config()
        return generate_plan(spec, config=config)

    def merge_plans(self, fresh: TestPlan, saved: TestPlan) -> MergeResult:
        """Merge user-edited intel from a saved plan into a fresh plan.

        Uses test case name (not id — ids are random uuids) as the matching
        key. Body fields merge with fresh-wins for schema changes, saved-wins
        for user-edited values.
        """
        saved_lookup: dict[str, TestCase] = {tc.name: tc for tc in saved.test_cases}
        kept = 0
        new = 0
        for tc in fresh.test_cases:
            old_tc = saved_lookup.pop(tc.name, None)
            if old_tc is not None:
                tc.path_params = old_tc.path_params
                tc.query_params = old_tc.query_params
                tc.headers = old_tc.headers
                tc.enabled = old_tc.enabled
                tc.body = _merge_body(tc.body, old_tc.body)
                kept += 1
            else:
                new += 1

        removed = len(saved_lookup)

        # Plan-level fields from saved plan win (auth, global headers)
        fresh.auth_type = saved.auth_type
        fresh.auth_value = saved.auth_value
        fresh.global_headers = saved.global_headers

        return MergeResult(plan=fresh, kept=kept, new=new, removed=removed)

    def generate_or_merge_plan(self, spec: ParsedSpec) -> tuple[TestPlan, MergeResult | None]:
        """Generate a fresh plan and merge it with any saved plan on disk.

        Returns (plan, merge_result) where merge_result is None if no saved
        plan existed.
        """
        fresh = self.generate_plan(spec)
        saved = self.storage.load_plan_for_spec(spec.title)
        if saved is None:
            return fresh, None
        merge = self.merge_plans(fresh, saved)
        return merge.plan, merge

    # ------------------------------------------------------------------
    # Plan persistence
    # ------------------------------------------------------------------

    def save_plan(self, plan: TestPlan) -> str:
        return self.storage.save_plan(plan)

    def load_saved_plan(self, spec_title: str) -> TestPlan | None:
        return self.storage.load_plan_for_spec(spec_title)

    def archive_plan(self, plan: TestPlan) -> str:
        return self.storage.archive_plan(plan)

    # ------------------------------------------------------------------
    # History
    # ------------------------------------------------------------------

    def save_run_to_history(self, report: Report) -> str:
        return self.storage.save_run(report)

    def list_history(self, spec_title: str, base_url: str, limit: int = 20) -> list[dict]:
        return self.storage.list_runs(spec_title, base_url, limit)

    def load_history_run(self, spec_title: str, base_url: str, filename: str) -> Report | None:
        return self.storage.load_run(spec_title, base_url, filename)


# ---------------------------------------------------------------------- #
# Internal helpers
# ---------------------------------------------------------------------- #


def _merge_body(fresh_body: Any, saved_body: Any) -> Any:
    """Merge saved user edits into the fresh body from an updated spec.

    - Fresh body has all fields the new spec requires (incl. newly added).
    - Saved body carries the user's edits.
    - Result: fresh body with saved values overlaid where keys match.
    """
    if fresh_body is None:
        return saved_body
    if saved_body is None:
        return fresh_body
    if isinstance(fresh_body, dict) and isinstance(saved_body, dict):
        merged = dict(fresh_body)
        for key, val in saved_body.items():
            if key in merged:
                merged[key] = _merge_body(merged[key], val)
            else:
                merged[key] = val
        return merged
    return saved_body
