"""Auto-generate test plans from parsed OpenAPI specs.

When AI is enabled (config.ai_enabled + model available), complex body
fields are generated by the LLM instead of Faker. The integration is
invisible to callers — `generate_plan()` simply returns richer test data
when AI is configured.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any, Callable

from specs_agent.models.plan import Assertion, AssertionType, TestCase, TestPlan
from specs_agent.models.spec import Endpoint, HttpMethod, Parameter, ParsedSpec

if TYPE_CHECKING:
    from specs_agent.ai.generator import AIGenerator
    from specs_agent.config import AppConfig

logger = logging.getLogger(__name__)


def generate_plan(
    spec: ParsedSpec,
    base_url: str | None = None,
    config: "AppConfig | None" = None,
) -> TestPlan:
    """Generate a TestPlan from a ParsedSpec.

    Rules:
    - One TestCase per endpoint + documented response status code
    - Success (2xx): assert status code + response schema if defined
    - Error (4xx/5xx): assert status code only
    - GET: no body, populate required params with placeholders
    - POST/PUT/PATCH: generate minimal body from request_body_schema
    - Mark cases with missing required params as needs_input
    """
    url = base_url or spec.base_url

    # Optionally create an AI generator for domain-specific field values
    ai: AIGenerator | None = None
    if config and config.ai_enabled:
        ai = _try_init_ai(config)

    plan = TestPlan(
        name=f"{spec.title} Test Plan",
        spec_title=spec.title,
        base_url=url,
        created_at=datetime.now(timezone.utc).isoformat(),
    )

    for endpoint in spec.endpoints:
        cases = _generate_cases_for_endpoint(endpoint, ai=ai)
        plan.test_cases.extend(cases)

        # AI: generate additional creative scenarios for this endpoint
        if ai:
            ai_cases, _drops = _generate_ai_scenarios(endpoint, ai)
            plan.test_cases.extend(ai_cases)

        # Capture x-performance SLAs
        if endpoint.performance_sla:
            key = f"{endpoint.method.value} {endpoint.path}"
            sla = endpoint.performance_sla
            plan.performance_slas[key] = {
                "p95_ms": sla.latency_p95_ms,
                "p99_ms": sla.latency_p99_ms,
                "throughput_rps": sla.throughput_rps,
                "timeout_ms": sla.timeout_ms,
            }

    return plan


def _generate_cases_for_endpoint(
    endpoint: Endpoint,
    ai: "AIGenerator | None" = None,
) -> list[TestCase]:
    cases: list[TestCase] = []

    # ── Happy path: one test per documented response ─────────────────
    for resp in endpoint.responses:
        is_success = 200 <= resp.status_code < 300
        name = f"{endpoint.method.value} {endpoint.path} → {resp.status_code}"

        assertions = [
            Assertion(
                type=AssertionType.STATUS_CODE,
                expected=resp.status_code,
                description=f"Expect status {resp.status_code}",
            )
        ]

        if is_success and resp.schema:
            assertions.append(
                Assertion(
                    type=AssertionType.RESPONSE_SCHEMA,
                    expected=resp.schema,
                    description="Validate response body schema",
                )
            )

        path_params, needs_input = _build_path_params(endpoint.parameters)
        query_params = _build_query_params(endpoint.parameters)
        # Always include body for methods that require it — servers often
        # reject with 400 before checking resource existence (404)
        body, _ai_fields = _build_request_body(endpoint, ai=ai)

        cases.append(
            TestCase(
                endpoint_path=endpoint.path,
                method=endpoint.method.value,
                name=name,
                description=resp.description or f"Test {endpoint.display_name} → {resp.status_code}",
                enabled=is_success,
                path_params=path_params,
                query_params=query_params,
                body=body,
                assertions=assertions,
                needs_input=needs_input,
                ai_fields=_ai_fields,
            )
        )

    # If no responses documented, create a basic smoke test
    if not endpoint.responses:
        path_params, needs_input = _build_path_params(endpoint.parameters)
        _smoke_body, _smoke_ai = _build_request_body(endpoint, ai=ai)
        cases.append(
            TestCase(
                endpoint_path=endpoint.path,
                method=endpoint.method.value,
                name=f"{endpoint.method.value} {endpoint.path} → smoke test",
                description=f"Smoke test for {endpoint.display_name}",
                enabled=True,
                path_params=path_params,
                query_params=_build_query_params(endpoint.parameters),
                body=_smoke_body,
                ai_fields=_smoke_ai,
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=200,
                        description="Expect success",
                    )
                ],
                needs_input=needs_input,
            )
        )

    # ── Sad path: negative test cases ────────────────────────────────
    cases.extend(_generate_negative_cases(endpoint))

    return cases


def _generate_negative_cases(endpoint: Endpoint) -> list[TestCase]:
    """Generate negative/sad-path test cases.

    Uses documented error responses from the spec when available.
    When the spec documents NO error responses, generates best-practice
    negative cases based on the endpoint structure (params, body, method).
    """
    cases: list[TestCase] = []
    method = endpoint.method.value
    path = endpoint.path
    path_params_list = [p for p in endpoint.parameters if p.location.value == "path"]

    # Collect documented error codes from the spec
    documented_errors: dict[int, str] = {}
    for resp in endpoint.responses:
        if resp.status_code >= 400:
            documented_errors[resp.status_code] = resp.description

    # If the spec has no documented errors, infer likely ones based on endpoint structure
    if not documented_errors:
        documented_errors = _infer_error_responses(endpoint)

    # For each documented error, generate an appropriate test case
    # (The happy-path loop already created disabled cases for these,
    #  but those have no triggering data. Here we craft data to trigger them.)

    if 404 in documented_errors and path_params_list:
        # 404: Send non-existent ID to trigger not-found
        bad_params = {}
        for p in path_params_list:
            if p.schema_type in ("integer", "int64", "int32"):
                bad_params[p.name] = "999999999"
            else:
                bad_params[p.name] = "nonexistent_id_000"
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 404 not found (trigger)",
                description=f"Sad path: {documented_errors[404]}",
                enabled=False,
                test_type="sad",
                path_params=bad_params,
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=404,
                        description=f"Spec: {documented_errors[404]}",
                    )
                ],
            )
        )

    if 400 in documented_errors:
        path_params_dict = _build_path_params_dict(endpoint.parameters)

        # 400: Empty body (for POST/PUT/PATCH)
        if method in ("POST", "PUT", "PATCH") and endpoint.request_body_schema:
            cases.append(
                TestCase(
                    endpoint_path=path,
                    method=method,
                    name=f"{method} {path} → 400 empty body (trigger)",
                    description=f"Sad path: {documented_errors[400]}",
                    enabled=False,
                    test_type="sad",
                    path_params=path_params_dict,
                    body={},
                    assertions=[
                        Assertion(
                            type=AssertionType.STATUS_CODE,
                            expected=400,
                            description=f"Spec: {documented_errors[400]}",
                        )
                    ],
                )
            )

        # 400: Missing required fields
        if method in ("POST", "PUT", "PATCH") and endpoint.request_body_schema:
            schema = endpoint.request_body_schema
            required_fields = schema.get("required", [])
            properties = schema.get("properties", {})

            for field in required_fields[:3]:
                partial_body = {}
                for prop_name, prop_schema in properties.items():
                    if prop_name == field:
                        continue
                    partial_body[prop_name] = _generate_sample_from_schema(prop_schema)

                cases.append(
                    TestCase(
                        endpoint_path=path,
                        method=method,
                        name=f"{method} {path} → 400 missing {field} (trigger)",
                        description=f"Sad path: required field '{field}' omitted — {documented_errors[400]}",
                        enabled=False,
                    test_type="sad",
                        path_params=path_params_dict,
                        body=partial_body,
                        assertions=[
                            Assertion(
                                type=AssertionType.STATUS_CODE,
                                expected=400,
                                description=f"Expect 400 when '{field}' missing",
                            )
                        ],
                    )
                )

        # 400: Invalid param type
        for p in path_params_list:
            if p.schema_type in ("integer", "int64", "int32", "number"):
                bad_type_params = _build_path_params_dict(endpoint.parameters)
                bad_type_params[p.name] = "not_a_number"
                cases.append(
                    TestCase(
                        endpoint_path=path,
                        method=method,
                        name=f"{method} {path} → 400 invalid {p.name} (trigger)",
                        description=f"Sad path: {p.name} expects {p.schema_type} — {documented_errors[400]}",
                        enabled=False,
                    test_type="sad",
                        path_params=bad_type_params,
                        assertions=[
                            Assertion(
                                type=AssertionType.STATUS_CODE,
                                expected=400,
                                description=f"Spec: {documented_errors[400]}",
                            )
                        ],
                    )
                )

    if 401 in documented_errors:
        # 401: No auth header
        path_params_dict = _build_path_params_dict(endpoint.parameters)
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 401 unauthorized (trigger)",
                description=f"Sad path: {documented_errors[401]}",
                enabled=False,
                test_type="sad",
                path_params=path_params_dict,
                headers={"Authorization": ""},  # Empty auth
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=401,
                        description=f"Spec: {documented_errors[401]}",
                    )
                ],
            )
        )

    if 403 in documented_errors:
        path_params_dict = _build_path_params_dict(endpoint.parameters)
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 403 forbidden (trigger)",
                description=f"Sad path: {documented_errors[403]}",
                enabled=False,
                test_type="sad",
                path_params=path_params_dict,
                headers={"Authorization": "Bearer invalid_token_000"},
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=403,
                        description=f"Spec: {documented_errors[403]}",
                    )
                ],
            )
        )

    if 409 in documented_errors:
        # 409: Conflict — try creating a duplicate
        path_params_dict = _build_path_params_dict(endpoint.parameters)
        body, _ai_fields = _build_request_body(endpoint, ai=ai)
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 409 conflict (trigger)",
                description=f"Sad path: {documented_errors[409]}",
                enabled=False,
                test_type="sad",
                path_params=path_params_dict,
                body=body,
                ai_fields=_ai_fields,
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=409,
                        description=f"Spec: {documented_errors[409]}",
                    )
                ],
            )
        )

    if 415 in documented_errors:
        path_params_dict = _build_path_params_dict(endpoint.parameters)
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 415 wrong content type (trigger)",
                description=f"Sad path: {documented_errors[415]}",
                enabled=False,
                test_type="sad",
                path_params=path_params_dict,
                headers={"Content-Type": "text/plain"},
                body="not json",
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=415,
                        description=f"Spec: {documented_errors[415]}",
                    )
                ],
            )
        )

    if 429 in documented_errors:
        path_params_dict = _build_path_params_dict(endpoint.parameters)
        cases.append(
            TestCase(
                endpoint_path=path,
                method=method,
                name=f"{method} {path} → 429 rate limited (trigger)",
                description=f"Sad path: {documented_errors[429]}",
                enabled=False,
                test_type="sad",
                path_params=path_params_dict,
                assertions=[
                    Assertion(
                        type=AssertionType.STATUS_CODE,
                        expected=429,
                        description=f"Spec: {documented_errors[429]}",
                    )
                ],
            )
        )

    # Any other documented error codes not specifically handled above
    handled = {400, 401, 403, 404, 409, 415, 429}
    for code, desc in documented_errors.items():
        if code not in handled:
            path_params_dict = _build_path_params_dict(endpoint.parameters)
            cases.append(
                TestCase(
                    endpoint_path=path,
                    method=method,
                    name=f"{method} {path} → {code} (spec-documented)",
                    description=f"Sad path: {desc}",
                    enabled=False,
                    test_type="sad",
                    path_params=path_params_dict,
                    assertions=[
                        Assertion(
                            type=AssertionType.STATUS_CODE,
                            expected=code,
                            description=f"Spec: {desc}",
                        )
                    ],
                )
            )

    return cases


def _infer_error_responses(endpoint: Endpoint) -> dict[int, str]:
    """Infer likely error responses based on endpoint structure when spec doesn't document them."""
    errors: dict[int, str] = {}
    method = endpoint.method.value
    has_path_params = any(p.location.value == "path" for p in endpoint.parameters)
    has_body = method in ("POST", "PUT", "PATCH") and endpoint.request_body_schema

    # Endpoints with path params likely return 404
    if has_path_params:
        errors[404] = "Resource not found (inferred)"

    # Endpoints with request body likely return 400
    if has_body:
        errors[400] = "Invalid request body (inferred)"

    return errors


def _build_path_params_dict(parameters: list[Parameter]) -> dict[str, str]:
    """Build path params dict without the needs_input tracking."""
    params: dict[str, str] = {}
    for p in parameters:
        if p.location.value != "path":
            continue
        if p.example is not None:
            params[p.name] = str(p.example)
        elif p.default is not None:
            params[p.name] = str(p.default)
        elif p.enum_values:
            params[p.name] = p.enum_values[0]
        else:
            params[p.name] = _smart_placeholder(p.name, p.schema_type)
    return params


def _build_path_params(parameters: list[Parameter]) -> tuple[dict[str, str], bool]:
    """Build path parameter values. Returns (params_dict, needs_input).

    needs_input is False when all params have examples, defaults, enums,
    or valid faker template variables. It's only True when we can't generate
    any reasonable value.
    """
    params: dict[str, str] = {}
    needs_input = False

    for p in parameters:
        if p.location.value != "path":
            continue
        if p.example is not None:
            params[p.name] = str(p.example)
        elif p.default is not None:
            params[p.name] = str(p.default)
        elif p.enum_values:
            params[p.name] = p.enum_values[0]
        else:
            # Smart placeholder uses a faker function — this resolves at runtime
            params[p.name] = _smart_placeholder(p.name, p.schema_type)
            # Faker functions are auto-resolved, so no user input needed

    return params, needs_input


def _build_query_params(parameters: list[Parameter]) -> dict[str, str]:
    """Build query parameter values for required params only."""
    params: dict[str, str] = {}
    for p in parameters:
        if p.location.value != "query":
            continue
        if not p.required:
            continue
        if p.example is not None:
            params[p.name] = str(p.example)
        elif p.default is not None:
            params[p.name] = str(p.default)
        elif p.enum_values:
            params[p.name] = p.enum_values[0]
        else:
            params[p.name] = _smart_placeholder(p.name, p.schema_type)
    return params


def _smart_placeholder(param_name: str, schema_type: str) -> str:
    """Generate a smart template placeholder based on parameter name and type."""
    name = param_name.lower()

    # Match by name patterns
    if "id" in name or "uuid" in name or "guid" in name:
        return "{{$guid}}"
    if "email" in name:
        return "{{$randomEmail}}"
    if "name" in name and "user" in name:
        return "{{$randomUserName}}"
    if "first" in name and "name" in name:
        return "{{$randomFirstName}}"
    if "last" in name and "name" in name:
        return "{{$randomLastName}}"
    if "name" in name:
        return "{{$randomName}}"
    if "phone" in name:
        return "{{$randomPhone}}"
    if "url" in name or "uri" in name:
        return "{{$randomUrl}}"
    if "ip" in name:
        return "{{$randomIP}}"
    if "city" in name:
        return "{{$randomCity}}"
    if "country" in name:
        return "{{$randomCountry}}"
    if "zip" in name or "postal" in name:
        return "{{$randomZip}}"
    if "address" in name or "street" in name:
        return "{{$randomStreet}}"
    if "company" in name or "org" in name:
        return "{{$randomCompany}}"
    if "date" in name:
        return "{{$randomDate}}"
    if "time" in name:
        return "{{$isoTimestamp}}"

    # Fall back by schema type
    if schema_type == "integer":
        return "{{$randomInt}}"
    if schema_type == "number":
        return "{{$randomFloat}}"
    if schema_type == "boolean":
        return "{{$randomBoolean}}"

    return "{{$randomWord}}"


def _build_request_body(
    endpoint: Endpoint,
    ai: "AIGenerator | None" = None,
) -> Any | None:
    """Generate a minimal request body from the schema.

    If an AI generator is available, complex fields are batch-generated by
    the LLM. Faker handles the rest.
    """
    if endpoint.method in (HttpMethod.GET, HttpMethod.DELETE, HttpMethod.HEAD, HttpMethod.OPTIONS):
        return None, []
    schema = endpoint.request_body_schema
    if not schema:
        return None, []

    # First generate the base body with Faker templates
    body = _generate_sample_from_schema(schema)

    # If AI is available and body is a dict, try to enhance complex fields
    ai_field_names: list[str] = []
    if ai and isinstance(body, dict) and schema.get("properties"):
        body, ai_field_names = _ai_enhance_body(
            body, schema, endpoint, ai,
        )

    return body, ai_field_names


def _ai_enhance_body(
    body: dict[str, Any],
    schema: dict,
    endpoint: Endpoint,
    ai: "AIGenerator",
) -> dict[str, Any]:
    """Replace Faker-generated values with AI-generated ones for complex fields.

    Collects all AI-eligible fields, batch-generates values, and overlays
    them onto the Faker-generated body. Fields the AI can't handle (or
    that fail to generate) keep their Faker values.
    """
    properties = schema.get("properties", {})
    fields_for_ai: list[dict[str, Any]] = []

    for prop_name, prop_schema in properties.items():
        if prop_name not in body:
            continue
        if not ai.should_use_ai(prop_name, prop_schema):
            continue
        fields_for_ai.append({
            "name": prop_name,
            "type": prop_schema.get("type", "string"),
            "description": prop_schema.get("description", ""),
            "enum": prop_schema.get("enum"),
            "format": prop_schema.get("format", ""),
        })

    if not fields_for_ai:
        return body, []

    # Batch LLM call for this endpoint
    try:
        ai_values = ai.generate_for_endpoint(
            fields_for_ai,
            endpoint.method.value,
            endpoint.path,
            endpoint.summary or endpoint.description,
        )
    except Exception as exc:
        logger.warning("AI generation failed for %s %s: %s", endpoint.method.value, endpoint.path, exc)
        return body, []

    # Overlay AI values onto the Faker body (AI wins where it succeeded)
    ai_field_names: list[str] = []
    for key, value in ai_values.items():
        if key in body and value is not None:
            body[key] = value
            ai_field_names.append(key)

    return body, ai_field_names


def _generate_sample_from_schema(schema: dict) -> Any:
    """Generate a minimal sample value from a JSON schema (Faker tier)."""
    schema_type = schema.get("type", "object")

    if schema_type == "object":
        properties = schema.get("properties", {})
        required = schema.get("required", [])
        obj: dict[str, Any] = {}
        for prop_name, prop_schema in properties.items():
            # Include required fields and a few optional ones
            if prop_name in required or len(obj) < 3:
                obj[prop_name] = _generate_sample_from_schema(prop_schema)
        return obj

    if schema_type == "array":
        items = schema.get("items", {})
        return [_generate_sample_from_schema(items)]

    if schema_type == "string":
        enum = schema.get("enum")
        if enum:
            return enum[0]
        fmt = schema.get("format", "")
        if fmt == "email":
            return "{{$randomEmail}}"
        if fmt == "date":
            return "{{$randomDate}}"
        if fmt == "date-time":
            return "{{$isoTimestamp}}"
        if fmt == "uri" or fmt == "url":
            return "{{$randomUrl}}"
        if fmt == "uuid":
            return "{{$guid}}"
        if fmt == "ipv4":
            return "{{$randomIP}}"
        if fmt == "ipv6":
            return "{{$randomIPv6}}"
        return "{{$randomWord}}"

    if schema_type == "integer":
        return schema.get("default", "{{$randomInt}}")

    if schema_type == "number":
        return schema.get("default", "{{$randomFloat}}")

    if schema_type == "boolean":
        return schema.get("default", "{{$randomBoolean}}")

    return None


# ------------------------------------------------------------------ #
# AI generator init helper
# ------------------------------------------------------------------ #


def _validate_ai_scenarios(
    scenarios: list[dict],
    endpoint: Endpoint,
) -> tuple[list[dict], list[str]]:
    """Drop scenarios that clearly don't make sense.

    Returns (kept, drop_reasons). Reasons are short human-readable strings
    suitable for surfacing in the progress feed / logs.
    """
    known_param_names = {p.name for p in endpoint.parameters}
    body_schema_props: set[str] = set()
    schema = endpoint.request_body_schema
    if schema and isinstance(schema.get("properties"), dict):
        body_schema_props = set(schema["properties"].keys())

    body_forbidden = endpoint.method in (
        HttpMethod.GET, HttpMethod.DELETE, HttpMethod.HEAD, HttpMethod.OPTIONS,
    )

    # Keys that typically appear in *response* error bodies — a happy-path
    # request body made only of these is almost certainly the LLM confusing
    # request with response.
    RESPONSE_SHAPE_KEYS = {"message", "error", "code", "status", "detail"}

    kept: list[dict] = []
    drops: list[str] = []

    for s in scenarios:
        name = s.get("name", "<unnamed>")
        status = s.get("expected_status")
        category = str(s.get("category", "")).lower()
        body = s.get("body")

        # 1. Status code in [100, 599]
        if not isinstance(status, int) or status < 100 or status > 599:
            drops.append(f"{name}: invalid expected_status {status!r}")
            continue
        is_sad = status >= 400

        # 1b. Category ↔ status coherence
        if category in ("invalid_input", "boundary", "security") and not is_sad:
            drops.append(f"{name}: {category} scenario shouldn't expect {status}")
            continue

        # 2. Param name sanity — every path/query key must be declared on the endpoint
        invented: list[str] = []
        for key in (s.get("path_params") or {}).keys():
            if key not in known_param_names:
                invented.append(f"path.{key}")
        for key in (s.get("query_params") or {}).keys():
            if key not in known_param_names:
                invented.append(f"query.{key}")
        if invented:
            drops.append(f"{name}: invented params {invented}")
            continue

        # 4. Body forbidden for GET/DELETE/HEAD/OPTIONS — we strip later too,
        # but warn if the LLM is persistently wrong.
        # (This is a soft check; we keep the scenario but note it.)
        # (Actual stripping happens in the materialize step.)

        # 5. Response-shape smell — a happy-path body consisting ONLY of
        # response-like keys with none of them in the request schema.
        if (
            not is_sad
            and not body_forbidden
            and isinstance(body, dict)
            and body
            and body_schema_props
        ):
            body_keys = set(body.keys())
            non_schema = body_keys - body_schema_props
            if body_keys.issubset(RESPONSE_SHAPE_KEYS) and non_schema == body_keys:
                drops.append(f"{name}: body looks like a response, not a request {list(body_keys)}")
                continue

        kept.append(s)

    return kept, drops


def _generate_ai_scenarios(
    endpoint: Endpoint,
    ai: "AIGenerator",
    on_phase: "Callable[[str, int], None] | None" = None,
) -> tuple[list[TestCase], list[str]]:
    """Ask the LLM to propose additional test scenarios for an endpoint.

    Returns (cases, drop_reasons). Drop reasons describe scenarios the
    validator rejected so the UI/logs can surface them.

    If `on_phase` is provided, it is invoked with (phase_name, raw_count)
    after the LLM returns raw scenarios but before validation — gives the
    WS layer a hook to emit a "validating…" progress event.
    """
    try:
        # Gather endpoint metadata for the prompt
        params = [
            {
                "name": p.name,
                "location": p.location.value if hasattr(p.location, "value") else str(p.location),
                "schema_type": p.schema_type,
                "description": p.description,
            }
            for p in endpoint.parameters
        ]
        documented_codes = [r.status_code for r in endpoint.responses]

        scenarios = ai.generate_scenarios(
            endpoint_method=endpoint.method.value,
            endpoint_path=endpoint.path,
            endpoint_description=endpoint.summary or endpoint.description,
            parameters=params,
            body_schema=endpoint.request_body_schema,
            documented_responses=documented_codes,
        )

        if on_phase:
            try:
                on_phase("validating", len(scenarios))
            except Exception:
                pass

        # Validation pass — drop obviously wrong scenarios before materialize.
        scenarios, drop_reasons = _validate_ai_scenarios(scenarios, endpoint)
        for reason in drop_reasons:
            logger.info("Dropped AI scenario for %s %s: %s",
                        endpoint.method.value, endpoint.path, reason)

        # Precompute rule-based defaults so AI scenarios inherit them when
        # the LLM omits fields (common for query_params, headers, and bodies
        # on PUT/POST where the scenario focuses on one aspect).
        default_query = _build_query_params(endpoint.parameters)
        default_body, default_ai_fields = _build_request_body(endpoint, ai=ai)

        cases: list[TestCase] = []
        for s in scenarios:
            name = f"{endpoint.method.value} {endpoint.path} → {s['expected_status']} ({s['name']})"
            expected_status = s["expected_status"]
            is_sad = expected_status >= 400
            assertions = [
                Assertion(
                    type=AssertionType.STATUS_CODE,
                    expected=expected_status,
                    description=s["description"],
                )
            ]

            # Path params — fall back to endpoint example/default when the
            # scenario doesn't specify the param.
            path_params: dict[str, str] = {}
            scenario_path = s.get("path_params") or {}
            for p in endpoint.parameters:
                if p.location.value == "path":
                    path_params[p.name] = str(
                        scenario_path.get(p.name, p.example or p.default or "1")
                    )

            # Query params — overlay scenario's values on top of rule-based defaults.
            query_params = {k: str(v) for k, v in default_query.items()}
            for k, v in (s.get("query_params") or {}).items():
                query_params[str(k)] = str(v)

            # Headers — copy what the scenario proposed; none inferred here.
            headers = {str(k): str(v) for k, v in (s.get("headers") or {}).items()}

            # Body — prefer the scenario's body, but fall back to the
            # rule-based one for methods that need a payload. Sad scenarios
            # are allowed to submit an empty/invalid body intentionally, so
            # only backfill when the scenario gave us nothing.
            # Methods without a request body (GET/DELETE/HEAD/OPTIONS) must
            # not carry one — the LLM sometimes returns the *response* body
            # in that slot, so drop it defensively.
            body_method_forbidden = endpoint.method in (
                HttpMethod.GET, HttpMethod.DELETE, HttpMethod.HEAD, HttpMethod.OPTIONS,
            )
            scenario_body = s.get("body")
            if body_method_forbidden:
                body = None
            else:
                body = scenario_body
                if body in (None, {}, "") and not is_sad:
                    body = default_body
            ai_fields: list[str]
            if isinstance(body, dict):
                ai_fields = list(body.keys())
            elif body is default_body:
                ai_fields = default_ai_fields
            else:
                ai_fields = []

            tc = TestCase(
                endpoint_path=endpoint.path,
                method=endpoint.method.value,
                name=name,
                description=f"[AI] {s['description']}",
                enabled=True,
                test_type="sad" if is_sad else "happy",
                path_params=path_params,
                query_params=query_params,
                headers=headers,
                body=body,
                assertions=assertions,
                ai_generated=True,
                ai_category=s.get("category", "edge_case"),
                ai_fields=ai_fields,
            )
            cases.append(tc)

        return cases, drop_reasons
    except Exception as exc:
        logger.warning("AI scenario generation failed for %s %s: %s",
                       endpoint.method.value, endpoint.path, exc)
        return [], []


def _try_init_ai(config: "AppConfig") -> "AIGenerator | None":
    """Attempt to create an AIGenerator from config. Returns None on failure."""
    try:
        from specs_agent.ai.generator import AIGenerator

        gen = AIGenerator(
            model_path=config.ai_model_path,
            model_size=config.ai_model_size,
            n_ctx=config.ai_n_ctx,
            n_gpu_layers=config.ai_n_gpu_layers,
            cache_dir=config.ai_cache_dir,
            backend=config.ai_backend,
            http_base_url=config.ai_http_base_url,
            http_model=config.ai_http_model,
            http_api_key=config.ai_http_api_key,
            provider=getattr(config, "ai_provider", ""),
            anthropic_api_key=getattr(config, "ai_anthropic_api_key", ""),
            anthropic_model=getattr(config, "ai_anthropic_model", "claude-haiku-4-5"),
            openai_api_key=getattr(config, "ai_openai_api_key", ""),
            openai_model=getattr(config, "ai_openai_model", "gpt-4o-mini"),
            openai_base_url=getattr(config, "ai_openai_base_url", ""),
        )
        if gen.is_available():
            logger.info("AI scenario generation enabled (model: %s)", gen.resolved_model_path)
            return gen
        logger.info("AI enabled in config but no model available — using Faker only")
        return None
    except Exception as exc:
        logger.warning("Failed to init AI generator: %s — using Faker only", exc)
        return None
